/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package design;

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.mail.*;
import javax.mail.internet.*;
import java.util.Properties;
import java.util.regex.Pattern;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.Set;
import java.sql.Date;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;

public class Chambre extends javax.swing.JPanel {

    /**
     * Creates new form Chambre2
     */
    public Chambre() {
        initComponents();
        afficherTable();
    }

    java.sql.PreparedStatement pst;
    java.sql.ResultSet res;
    java.sql.ResultSetMetaData result;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        txtNumChambre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtDesign = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPrixNuite = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnModifier = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnEffaccer = new javax.swing.JButton();
        btnAjouter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        chambreTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        txtRecherche = new javax.swing.JTextField();
        btnRechercher1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        dateEntree = new com.toedter.calendar.JDateChooser();
        btnRechercher2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1350, 850));
        setPreferredSize(new java.awt.Dimension(1230, 850));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        txtNumChambre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumChambreActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(3, 45, 76));
        jLabel1.setText("Numéro de la Chambre");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(3, 45, 76));
        jLabel3.setText("Designation");

        txtType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(3, 45, 76));
        jLabel2.setText("Type");

        txtPrixNuite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrixNuiteActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(3, 45, 76));
        jLabel4.setText("Prix Nuité");

        btnModifier.setBackground(new java.awt.Color(10, 73, 105));
        btnModifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/image/modifier.png"))); // NOI18N
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnSupprimer.setBackground(new java.awt.Color(10, 73, 105));
        btnSupprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/image/supprimer.png"))); // NOI18N
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(3, 45, 76));
        jLabel10.setText("Formulaire  pour enregistrer les chambres");

        btnEffaccer.setBackground(new java.awt.Color(10, 73, 105));
        btnEffaccer.setForeground(new java.awt.Color(255, 255, 255));
        btnEffaccer.setText("Effacer");
        btnEffaccer.setBorder(null);
        btnEffaccer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEffaccerActionPerformed(evt);
            }
        });

        btnAjouter.setBackground(new java.awt.Color(10, 73, 105));
        btnAjouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/image/ajouter.png"))); // NOI18N
        btnAjouter.setBorder(null);
        btnAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(115, 115, 115))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumChambre)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                            .addComponent(txtDesign)
                            .addComponent(txtType)
                            .addComponent(txtPrixNuite)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnEffaccer, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabel2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel4))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabel3)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumChambre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDesign, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPrixNuite, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEffaccer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnModifier, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSupprimer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 160, 410, 490));

        chambreTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Numero Chambre", "Design", "Type", "Prix Nuite"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        chambreTable.setColumnSelectionAllowed(true);
        chambreTable.setRowHeight(40);
        chambreTable.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                chambreTableFocusGained(evt);
            }
        });
        chambreTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chambreTableMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                chambreTableMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(chambreTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 800, 560));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnRechercher1.setBackground(new java.awt.Color(10, 73, 105));
        btnRechercher1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/image/chercher.png"))); // NOI18N
        btnRechercher1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercher1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(txtRecherche, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnRechercher1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRechercher1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRecherche, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 18, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 800, -1));

        jPanel4.setBackground(new java.awt.Color(10, 73, 105));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/image/chambre.png"))); // NOI18N
        jLabel5.setText("CHAMBRE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(474, 474, 474)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(620, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1350, 120));

        jPanel5.setBackground(new java.awt.Color(3, 45, 76));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/image/supprimer.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(1181, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(139, 139, 139))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1350, 40));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(3, 45, 76));
        jLabel12.setText("Recherche des chambres libres");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(3, 45, 76));
        jLabel9.setText("Date à rechercher :");

        btnRechercher2.setBackground(new java.awt.Color(10, 73, 105));
        btnRechercher2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/image/chercher.png"))); // NOI18N
        btnRechercher2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRechercher2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateEntree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRechercher2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(38, 38, 38))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnRechercher2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateEntree, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(109, 109, 109))
        );

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 650, 380, 170));
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrixNuiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrixNuiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrixNuiteActionPerformed

    private void btnAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouterActionPerformed
        try {
            String numC = txtNumChambre.getText();
            String des = txtDesign.getText();
            String t = txtType.getText();
            int prixN = Integer.parseInt(txtPrixNuite.getText());

            if (!numC.isBlank() && !des.isBlank() && !t.isBlank() || prixN > 0) {

                int conf = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment ajouter cette chambre ? ");
                if (conf == JOptionPane.YES_OPTION) {

                    pst = Connexion.connBD().prepareStatement("INSERT INTO chambre(numchambre,design,type,prixnuite) VALUES (?,?,?,?)");
                    pst.setString(1, numC);
                    pst.setString(2, des);
                    pst.setString(3, t);
                    pst.setInt(4, prixN);

                    int k = pst.executeUpdate();
                    if (k == 1) {
                        JOptionPane.showConfirmDialog(this, "La chambre numero " + numC + " est ajoute avec succes!", "Message de succes", JOptionPane.INFORMATION_MESSAGE);
                        effacerChamps();
                        afficherTable();
                    } else {
                        JOptionPane.showConfirmDialog(this, "Erreur, veuillez reessayer!", "Message d'erreur", JOptionPane.ERROR_MESSAGE);
                    }

                }

            } else {

                JOptionPane.showConfirmDialog(this, "Erreur, veuillez saisir toutes les donnees!", "Message d'erreur", JOptionPane.ERROR_MESSAGE);

            }

        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(this, "Erreur, veuillez reessayer!\n" + ex, "Message d'erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAjouterActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
        try {

            String numCh = txtNumChambre.getText();
            String desi = txtDesign.getText();
            String ty = txtType.getText();
            int pN = Integer.parseInt(txtPrixNuite.getText());

            if (!numCh.isBlank() && !desi.isBlank() && !ty.isBlank() || pN > 0) {

                int conf = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment modifier la chambre numero " + numCh + " ?");

                if (conf == JOptionPane.YES_OPTION) {

                    pst = Connexion.connBD().prepareStatement("UPDATE chambre SET design=?,type=?,prixnuite=? WHERE numchambre=?");
                    pst.setString(1, desi);
                    pst.setString(2, ty);
                    pst.setInt(3, pN);
                    pst.setString(4, numCh);

                    if (pst.executeUpdate() == 1) {
                        JOptionPane.showConfirmDialog(this, "La chambre numero " + numCh + " est modifie avec succes!", "Message de succes", JOptionPane.INFORMATION_MESSAGE);
                        effacerChamps();
                        afficherTable();
                    }
                }
            }

        } catch (SQLException ex) {
            JOptionPane.showConfirmDialog(this, ex, "Message de succes", JOptionPane.INFORMATION_MESSAGE);
            Logger.getLogger(Chambre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
        try {
            String numC = txtNumChambre.getText();
            int conf = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment supprimer la chambre numero " + numC + " ?");

            if (conf == JOptionPane.YES_OPTION) {
                pst = Connexion.connBD().prepareStatement("DELETE from chambre WHERE numchambre = ?");
                pst.setString(1, numC);
                int k = pst.executeUpdate();
                if (k == 1) {
                    JOptionPane.showMessageDialog(this, "La chambre numero " + numC + " est supprimé avec succées!", "Message de succes", JOptionPane.INFORMATION_MESSAGE);
                    effacerChamps();
                    afficherTable();
                } else {
                    JOptionPane.showMessageDialog(this, " Erreur, veuillez reessayer!", "Message d'erreur", JOptionPane.ERROR_MESSAGE);
                }

            }

        } catch (SQLException ex) {
            Logger.getLogger(Chambre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSupprimerActionPerformed

    public boolean verificationChambreLibre(String num, ArrayList<String> chambreNonLibre) {

        for (String numNonLibre : chambreNonLibre) {
            System.out.println(num + " == " + numNonLibre);
            if (num.equals(numNonLibre)) {
                return false;
            }
        }

        return true;
    }

    public void listeChambreLibre(java.sql.Date dateEntree) {
        ArrayList<String> chambreLibre = new ArrayList<String>();
        ArrayList<String> chambreNonLibre = new ArrayList<String>();
        try {
            PreparedStatement stmt2 = Connexion.connBD().prepareStatement("SELECT * from reserver where dateentree = ? ");
            stmt2.setDate(1, dateEntree);
            ResultSet resultat2 = stmt2.executeQuery();
            while (resultat2.next()) {
                String numChambres = resultat2.getString("numchambre");
                chambreNonLibre.add(numChambres);
            }

            PreparedStatement stmt3 = Connexion.connBD().prepareStatement("SELECT * from sejourner where dateentreesejour= ? ");
            stmt3.setDate(1, dateEntree);
            ResultSet resultat3 = stmt3.executeQuery();
            while (resultat3.next()) {
                String numChambres = resultat3.getString("numchambre");
                chambreNonLibre.add(numChambres);
            }

            Set<String> set = new LinkedHashSet<String>();
            set.addAll(chambreNonLibre);
            chambreNonLibre.clear();
            chambreNonLibre.addAll(set);

            String listeN = String.join(",", chambreNonLibre);
            System.out.println("liste non Libre" + listeN);

            // obtenir les listes de tous les chambres  
            PreparedStatement stmt = Connexion.connBD().prepareStatement("SELECT * from chambre order by numchambre ASC ");
            ResultSet resultat = stmt.executeQuery();
            while (resultat.next()) {
                String num = resultat.getString("numchambre");
                System.out.println("pour num =" + num + " =>" + verificationChambreLibre(num, chambreNonLibre));

                if (verificationChambreLibre(num, chambreNonLibre) == true) {
                    chambreLibre.add(num);
                }

            }

//            String liste = String.join(",", chambreLibre);
//            System.out.println("liste libre "+liste);
            affichageRechercheChambreLibre(chambreLibre);

        } catch (Exception e1) {
            System.out.println(e1);
        }

    }

    private void affichageRechercheChambreLibre(ArrayList<String> chambreLibre) {

        try {
            DefaultTableModel df = (DefaultTableModel) chambreTable.getModel();
            df.setRowCount(0);
            for (String n : chambreLibre) {
                PreparedStatement stmt4 = Connexion.connBD().prepareStatement("SELECT * from chambre where numchambre = ? ");
                stmt4.setString(1, n);
                ResultSet resultat4 = stmt4.executeQuery();

                while (resultat4.next()) {
                    Vector v2 = new Vector();
                    v2.add(resultat4.getString("numchambre"));
                    v2.add(resultat4.getString("design"));
                    v2.add(resultat4.getString("type"));
                    v2.add(resultat4.getString("prixnuite"));
                    df.addRow(v2);

                }

                System.out.println("n = " + n);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }

    }


    private void chambreTableFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_chambreTableFocusGained

    }//GEN-LAST:event_chambreTableFocusGained

    private void chambreTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chambreTableMouseClicked
        try {
            int i = chambreTable.getSelectedRow();
            TableModel tm = chambreTable.getModel();
            txtNumChambre.setText(tm.getValueAt(i, 0).toString());
            txtDesign.setText(tm.getValueAt(i, 1).toString());
            txtType.setText(tm.getValueAt(i, 2).toString());
            txtPrixNuite.setText(tm.getValueAt(i, 3).toString());
        } catch (Exception e) {
            JOptionPane.showConfirmDialog(this, "Erreur, veuillez reessayer! \n" + e, "Message d'erreur", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_chambreTableMouseClicked

    private void chambreTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chambreTableMousePressed

    }//GEN-LAST:event_chambreTableMousePressed

    private void txtTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeActionPerformed

    private void txtNumChambreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumChambreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumChambreActionPerformed

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel11MouseClicked

    private void btnEffaccerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEffaccerActionPerformed
        effacerChamps();
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEffaccerActionPerformed

    private void btnRechercher1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercher1ActionPerformed
        // TODO add your handling code here:

        String rec = txtRecherche.getText();
        try {
            int q;
            if (rec == null) {
                try {
                    afficherTable();
                } catch (Exception e) {
                    JOptionPane.showConfirmDialog(this, "Erreur\n" + e, "Message d'erreur", JOptionPane.ERROR_MESSAGE);
                }
            } else {

                String sql = "SELECT * FROM chambre WHERE numchambre LIKE ? OR design LIKE ? OR type LIKE ? OR prixnuite::text LIKE ?";

                PreparedStatement pst = null;
                try {
                    pst = Connexion.connBD().prepareStatement(sql);
                } catch (SQLException ex) {
                    Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
                }
                pst.setString(1, "%" + rec + "%");
                pst.setString(2, "%" + rec + "%");
                pst.setString(3, "%" + rec + "%");
                pst.setString(4, "%" + rec + "%");

                res = pst.executeQuery();
                result = res.getMetaData();
                q = result.getColumnCount();
                DefaultTableModel df = (DefaultTableModel) chambreTable.getModel();
                df.setRowCount(0);
                while (res.next()) {
                    Vector v2 = new Vector();
                    for (int a = 1; a <= q; a++) {
                        v2.add(res.getString("numchambre"));
                        v2.add(res.getString("design"));
                        v2.add(res.getString("type"));
                        v2.add(res.getString("prixnuite"));
                    }
                    df.addRow(v2);
                }
            }
            txtRecherche.setText("");
        } catch (SQLException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRechercher1ActionPerformed

    private void btnRechercher2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRechercher2ActionPerformed
        // TODO add your handling code here:

        java.sql.Date dE = new java.sql.Date(dateEntree.getDate().getTime());

        java.sql.Date dateActuelle = new java.sql.Date(new java.util.Date().getTime());

        java.time.LocalDate de = dE.toLocalDate();
        java.time.LocalDate da = dateActuelle.toLocalDate();

        long r = java.time.temporal.ChronoUnit.DAYS.between(de, da);
        
        if (r <= 0){
             listeChambreLibre(dE);
        }
        else JOptionPane.showMessageDialog(this, "Veuillez entrer une date qui n'est pas encore dépassée ! "); 

       
    }//GEN-LAST:event_btnRechercher2ActionPerformed

    private void afficherTable() {
        try {
            int q;
            pst = Connexion.connBD().prepareStatement("SELECT * from chambre order by numchambre");
            res = pst.executeQuery();
            result = res.getMetaData();
            q = result.getColumnCount();
            DefaultTableModel df = (DefaultTableModel) chambreTable.getModel();
            df.setRowCount(0);
            while (res.next()) {
                Vector v = new Vector();
                for (int a = 1; a <= q; a++) {
                    v.add(res.getString("numchambre"));
                    v.add(res.getString("design"));
                    v.add(res.getString("type"));
                    v.add(res.getString("prixnuite"));
                }
                df.addRow(v);
            }

        } catch (SQLException ex) {
            Logger.getLogger(Chambre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void effacerChamps() {

        txtNumChambre.setText("");
        txtDesign.setText("");
        txtType.setText("");
        txtPrixNuite.setText("");

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnEffaccer;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnRechercher1;
    private javax.swing.JButton btnRechercher2;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JTable chambreTable;
    private com.toedter.calendar.JDateChooser dateEntree;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDesign;
    private javax.swing.JTextField txtNumChambre;
    private javax.swing.JTextField txtPrixNuite;
    private javax.swing.JTextField txtRecherche;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables
}
