/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package design;

import java.sql.*;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author nirin
 */
public class Occuper extends javax.swing.JPanel {

    private Solde solde ;
    
    public Occuper( Solde solde) {
        this.solde = solde;
        
        initComponents();
        afficherOccuper();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void afficherOccuper() {
        try {
            PreparedStatement req;
            ResultSet res;
            req = Connexion.connBD().prepareStatement("SELECT * FROM occuper order by idoccup ASC");
            res = req.executeQuery();
            ResultSetMetaData rs = res.getMetaData();

            DefaultTableModel df = (DefaultTableModel) tableauOccuper.getModel();
            df.setRowCount(0);
            while (res.next()) {
                Vector v = new Vector();

                v.add(res.getString("idoccup"));
                v.add(res.getString("idreserv"));

                df.addRow(v);
            }
        } catch (SQLException ex) {

        }
    }

    public void ajouterOccuper(int idreserv, int montant) {

        int conf = JOptionPane.showConfirmDialog(null, " Voulez-vous vraiment ajouter cette nouvelle occupation ?");

        if (conf == JOptionPane.YES_OPTION){
            PreparedStatement stmt;
            try {
                stmt = Connexion.connBD().prepareStatement("INSERT INTO occuper (idreserv) VALUES (?) ");
                stmt.setInt(1, idreserv);
                stmt.executeUpdate();
                updateSolde(montant);         
                afficherOccuper();

            } catch (Exception e) {
                System.out.println(e);
            }

        }

    }

    public void modifierOccuper(int idoccup, int idreserv, int montant) {

        int conf = JOptionPane.showConfirmDialog(null, " Voulez-vous vraiment modifier cette occupation ?");

        if (conf == JOptionPane.YES_OPTION) {
            PreparedStatement stmt;
            try {

                stmt = Connexion.connBD().prepareStatement("UPDATE occuper set idreserv = ?  where idoccup = ? ");
                stmt.setInt(1, idreserv);
                stmt.setInt(2, idoccup);
                stmt.executeUpdate();

                updateSolde(montant);

                afficherOccuper();

            } catch (Exception e) {
                System.out.println(e);
            }
        }

    }

    public void updateSolde(int montant) {
        PreparedStatement stmt;
        try {
            stmt = Connexion.connBD().prepareStatement("INSERT INTO solde (solde) VALUES (?)");
            stmt.setInt(1, montant);
            stmt.executeUpdate();
            solde.afficherSolde();
        } catch (Exception e) {
            System.out.println(e);
        }
   }

    public void supprimerOccuper(int idoccup, int montant) {

        int conf = JOptionPane.showConfirmDialog(null, " Voulez-vous vraiment supprimer cette occupation ?");

        if (conf == JOptionPane.YES_OPTION) {
            PreparedStatement stmt;
            try {

                stmt = Connexion.connBD().prepareStatement("DELETE FROM  occuper where idoccup = ? ");
                stmt.setInt(1, idoccup);
                stmt.executeUpdate();
                updateSolde(montant);
                afficherOccuper();
                
            } catch (Exception e) {
                System.out.println(e);
            }
        }

    }
  
   private  void effacerChamps(){
      idoccupOc.setValue(0);
      idreservOc.setValue(0);
      montantOc.setText("0");
      montantPrec.setValue(0);
      
   }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableauOccuper = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnAjouter_occuper = new javax.swing.JButton();
        btnModifier_occuper = new javax.swing.JButton();
        btnSupprimer_occuper = new javax.swing.JButton();
        btnEffacer_occuper = new javax.swing.JButton();
        montantOc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        idreservOc = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        montantPrec = new javax.swing.JSpinner();
        idoccupOc = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(3, 45, 76));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/image/supprimer.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(1186, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -50, 1230, 90));

        jPanel2.setBackground(new java.awt.Color(10, 73, 105));
        jPanel2.setPreferredSize(new java.awt.Dimension(1230, 120));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/image/occuper.png"))); // NOI18N
        jLabel5.setText("OCCUPER");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(470, 470, 470)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(504, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, 110));

        tableauOccuper.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Id Occuper", "Id Reservation"
            }
        ));
        tableauOccuper.setRowHeight(40);
        tableauOccuper.setShowGrid(true);
        tableauOccuper.setShowHorizontalLines(false);
        tableauOccuper.setShowVerticalLines(false);
        tableauOccuper.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableauOccuperMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableauOccuper);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 740, 610));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(3, 45, 76));
        jLabel10.setText("Formulaire pour les occupations des reservations ");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(3, 45, 76));
        jLabel2.setText("Identifiant de la Reservation ");

        btnAjouter_occuper.setBackground(new java.awt.Color(10, 73, 105));
        btnAjouter_occuper.setForeground(new java.awt.Color(255, 255, 255));
        btnAjouter_occuper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/image/ajouter.png"))); // NOI18N
        btnAjouter_occuper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAjouter_occuperActionPerformed(evt);
            }
        });

        btnModifier_occuper.setBackground(new java.awt.Color(10, 73, 105));
        btnModifier_occuper.setForeground(new java.awt.Color(255, 255, 255));
        btnModifier_occuper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/image/modifier.png"))); // NOI18N
        btnModifier_occuper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifier_occuperActionPerformed(evt);
            }
        });

        btnSupprimer_occuper.setBackground(new java.awt.Color(10, 73, 105));
        btnSupprimer_occuper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/design/image/supprimer.png"))); // NOI18N
        btnSupprimer_occuper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimer_occuperActionPerformed(evt);
            }
        });

        btnEffacer_occuper.setBackground(new java.awt.Color(10, 73, 105));
        btnEffacer_occuper.setForeground(new java.awt.Color(255, 255, 255));
        btnEffacer_occuper.setText("Effacer");
        btnEffacer_occuper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEffacer_occuperActionPerformed(evt);
            }
        });

        montantOc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        montantOc.setBorder(null);
        montantOc.setEnabled(false);
        montantOc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montantOcActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(3, 45, 76));
        jLabel3.setText("Montant");

        idreservOc.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                idreservOcStateChanged(evt);
            }
        });

        jButton1.setText("Afficher le montant");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnEffacer_occuper, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnAjouter_occuper, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnModifier_occuper, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnSupprimer_occuper, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(montantOc, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(130, 130, 130))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(idreservOc, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(idreservOc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(montantOc, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSupprimer_occuper, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAjouter_occuper, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModifier_occuper, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEffacer_occuper, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(164, 164, 164))
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 150, 420, 650));
        add(montantPrec, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 820, -1, -1));
        add(idoccupOc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 820, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked

        System.exit(0);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void btnEffacer_occuperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEffacer_occuperActionPerformed
        effacerChamps();
                         
    }//GEN-LAST:event_btnEffacer_occuperActionPerformed

    private void btnSupprimer_occuperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimer_occuperActionPerformed
        // TODO add your handling code here:
           int montantPrecedent = (int)montantPrec.getValue();
           int idoccup = (int) idoccupOc.getValue();
           supprimerOccuper(idoccup , montantPrecedent);       
        
    }//GEN-LAST:event_btnSupprimer_occuperActionPerformed

    private void btnModifier_occuperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifier_occuperActionPerformed
        int montantPrecedent = (int)montantPrec.getValue();
        updateSolde(montantPrecedent);
        
        int idoccup = (int) idoccupOc.getValue();
        int idreserv = (int)idreservOc.getValue();
        int solde =Integer.parseInt(montantOc.getText());
        modifierOccuper(idoccup,idreserv,solde);
          

    }//GEN-LAST:event_btnModifier_occuperActionPerformed

    private void btnAjouter_occuperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAjouter_occuperActionPerformed
        int idreserv = (int)idreservOc.getValue();
        int solde =Integer.parseInt(montantOc.getText());
        ajouterOccuper(idreserv,solde);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnAjouter_occuperActionPerformed

    private void montantOcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montantOcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montantOcActionPerformed

    private void tableauOccuperMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableauOccuperMouseClicked
        try{
            int i = tableauOccuper.getSelectedRow();

            selectionnerOcc(i);

        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Erreur lors de la  séléction", "message", HEIGHT);
        }

        
    }//GEN-LAST:event_tableauOccuperMouseClicked

    private void idreservOcStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_idreservOcStateChanged
       
            
                // TODO add your handling code here:
    }//GEN-LAST:event_idreservOcStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int idreserv = (int)idreservOc.getValue();
        System.out.println("ksslsl");
        afficherMontant(idreserv);
    }//GEN-LAST:event_jButton1ActionPerformed

    public void afficherMontant(int idreserv){
        try{
            PreparedStatement stmt = Connexion.connBD().prepareStatement("SELECT * FROM reserver where idreserv = ?");
            stmt.setInt(1,idreserv);
            ResultSet res = stmt.executeQuery();
            while (res.next()){

                String numchambre = res.getString("numchambre");
                int nbrjour = res.getInt("nbrjours");

                int solde = 0;
                String[] nums = numchambre.split(",");
                for (String num : nums) {
                    stmt = Connexion.connBD().prepareStatement(" SELECT  * from chambre where numchambre = ? ");
                    stmt.setString(1, num);

                    res = stmt.executeQuery();
                    while (res.next()) {
                        solde += (nbrjour * res.getInt("prixnuite"));
                    }
                }               
                montantOc.setText("" + solde + "");
                montantPrec.setValue((-1)*solde);
            
            }
        }
        catch( Exception e ){
            System.out.println(e);
        }  
    } 
  
    public void selectionnerOcc(int i){  
            try{               
            TableModel model = (TableModel) tableauOccuper.getModel();         
            idoccupOc.setValue(Integer.parseInt(model.getValueAt(i, 0).toString()));  
            idreservOc.setValue(Integer.parseInt(model.getValueAt(i, 1).toString()));
   
            int idreserv = Integer.parseInt(model.getValueAt(i, 1).toString());
                   afficherMontant(idreserv);
            }   
            
      
        catch(Exception e){
            System.out.println(e);
        } 
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter_occuper;
    private javax.swing.JButton btnEffacer_occuper;
    private javax.swing.JButton btnModifier_occuper;
    private javax.swing.JButton btnSupprimer_occuper;
    private javax.swing.JSpinner idoccupOc;
    private javax.swing.JSpinner idreservOc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField montantOc;
    private javax.swing.JSpinner montantPrec;
    private javax.swing.JTable tableauOccuper;
    // End of variables declaration//GEN-END:variables
}
